import './global.css';
import { Toaster } from "react-hot-toast"

export const metadata = {
    title: 'Welcome to task-for-finzarc',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
